version: "2"

services:
  api:
    build: .
    command: sh -c "python manage.py collectstatic && python manage.py migrate && gunicorn api.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers=3 --threads=2 --worker-connections=1000"
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:12
    container_name: api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB : dataplane
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

    networks:
      - my-network

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/var/lib/redis/data
    #      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  db-data:
  redis-data:

networks:
  my-network:
    driver: bridge