# Generated by Django 3.0.2 on 2020-01-11 12:04

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_data', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('dataframe', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
