# Generated by Django 3.0.2 on 2020-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
