# Generated by Django 2.2.5 on 2020-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataframe',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
